# Generated by Django 4.1.7 on 2023-03-29 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_bookreview_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookreview',
            name='comment',
            field=models.TextField(max_length=500),
        ),
    ]
