# Generated by Django 4.1.7 on 2023-03-29 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_bookreview_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookreview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
