# Generated by Django 4.1.7 on 2023-03-30 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_alter_bookreview_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookreview',
            name='comment',
            field=models.TextField(),
        ),
    ]
